### ISSUE TITLE
Contact you

### ISSUE THREAD

**Issue by freeyland** [onlab/BalnoWorkflow#2]
Dear,

Is there a way I can contact you to ask some questions. I really like your work.

Thx,
Frederick from Belgium

**Comment by onlab** [comment]
Hi, Frederick, how are you?

I'm sorry for being late. I didn't see your e-mail before.

Here is my e-mail: marcus@onlab.org

If you want I may join the freenode.org IRC network as mfernandez if you
prefer.

Bests,
Marcus Fernandez

**Comment by onlab** [comment]
@freeyland we may chat on freenode.org [nickname mfernandez] or mfernandez@onlab.org
